### ISSUE TITLE
datacenters.network

### ISSUE THREAD

**Issue by williamdes** [cloudsimplus/cloudsimplus#481]
Hello,

I discovered that you use a domain I own "datacenters.network" in your package name.
This is not a big deal, but maybe someone on this project would want to adopt the domain "datacenters.network" or "datacenters.eu" ?

"datacenters.network" is not yet ready for adoption, but in months it should be

**Comment by jlxcsong** [comment]
您好！您发的邮件我已收到！

**Comment by manoelcampos** [comment]
Hello @williamdes 
datacenters.network is not a domain name, but a subdomain inside org.cloudsimplus domain.
Subdomain clash is expected to happen all the time and it's not an issue, mainly because subdomains are expected to have regular common names that are used everywhere.

Therefore, that is not to worry here and no action is required.

**Comment by williamdes** [comment]
> datacenters.network is not a domain name

It is a domain name in the internet way, that said I am slowly abandoning it.
https://datacenters.network

Good to know that no action is needed

**Comment by manoelcampos** [comment]
What I meant is that, inside my project, datacenters.network is not a domain name, but a subdomain: org.cloudsimplus.datacenters.network. 

This way, there is no domain clash.
