### ISSUE TITLE
Simulation cannot be stopped when there are no available host resources to create a virtual machine

### ISSUE THREAD

**Issue by shijili** [cloudsimplus/cloudsimplus#485]
![Uploading 屏幕截图 2024-04-23 182111.png…]()

**Comment by shijili** [comment]
![屏幕截图 2024-04-23 182111](https://github.com/cloudsimplus/cloudsimplus/assets/155445121/badfece6-659c-4847-940c-a0f11fe17a4b)

**Comment by tgasla** [comment]
This is not a bug. This is the expected behavior. When there are not enough resources to place a cloudlet to a VM or a VM to a host, the simulation does not end if you do not tell it to do using the terminateAt call. The simulation keeps running and retries to place the VM (or the cloudlet) at the next time event that it is determined using minTimeBetweenEvents.

**Comment by shijili** [comment]
Thanks, I've prevented this by having an event listener terminate the simulation after a specified time
